### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by jconroy** [chmac/wp-mail-smtp#7]
Hi @chmac great plugin! Was wondering if there is any chance you'd considering tagging versions on this repo to match those released via wp.org?

**Comment by chmac** [comment]
This repo doesn't have all the releases. I couldn't get svn and git to play nicely together so in the end I added `.git` to the svn exclude file and I did `git init` inside the `trunk` folder inside the `svn checkout`.

What prompted the question?

**Comment by jconroy** [comment]
> What prompted the question?
I was just wanting to be able to select different versions (for testing etc) - having the versions tagged just makes switching much easier when managing the plugin using git.

Means I can also pin a specific release version more easily if I use the repo as a submodule in projects.

At the moment I'd have to trawl through the commit history (https://github.com/chmac/wp-mail-smtp/commits/master) and puzzle together which commit signifies a new release.

**Comment by chmac** [comment]
Hmm, I see the use case. Unfortunately I don't see an easy fix. I can try to remember to tag versions as I release them, but not 100% sure that I will remember. I'm open to a PR if you want to submit one. Not sure that you can submit tags as a PR, but maybe I can pull them from your branch or something.

Bottom line, my defacto release strategy is via svn as that's how the plugin actually gets released to the world. This git repo is just a convenience for me as I much prefer working in git.

**Comment by jconroy** [comment]
No worries. If I can get a chance and it becomes enough of a pain point I'll see what I can help figure out.
